### ISSUE TITLE
Add strategy to find links by configuration

### ISSUE THREAD

**Issue by alextercete** [alextercete/homy#3]
Given the following folder structure:

``` text
`-- vim
    |-- .vim
    |   `-- [...]
    |-- .gvimrc
    |-- .vimrc
    |-- _gvimrc
    |-- _vimrc
    |-- _vsvimrc
    `-- symlinks.yml
```

And the configuration file `symlinks.yml`:

``` yaml
default:
  - .vim
  - .vimrc
  - .gvimrc
windows:
  - vimfiles -> .vim
  - _vimrc
  - _gvimrc
  - _vsvimrc
```

Then the following symbolic links should be created:
#### On Windows

``` text
~/vimfiles -> path/to/vim/.vim
~/.gvimrc -> path/to/vim/.gvimrc
~/.vimrc -> path/to/vim/.vimrc
~/_gvimrc -> path/to/vim/_gvimrc
~/_vimrc -> path/to/vim/_vimrc
~/_vsvimrc -> path/to/vim/_vsvimrc
```
#### On other platforms

``` text
~/.vim -> path/to/vim/.vim
~/.gvimrc -> path/to/vim/.gvimrc
~/.vimrc -> path/to/vim/.vimrc
```
